### ISSUE TITLE
fourseven:scss and meta:susy version compatibility 

### ISSUE THREAD

**Issue by nevace** [andreioprisan/meteor-breakpoint-sass#1]
Hi,

Thanks for the breakpoint package. SCSS is pushed back to 1.0.0 (from 2.0.0) and susy pushed back to 1.0.2 (from 2.1.1) when adding the package. Will there be compatibility with these any time soon?

**Comment by nagarajay** [comment]
Hi,

Thanks for the package. Can you please update the package as now fourseven:scss is at version 3.1.1. I hope you plan to make the package compatible.

**Comment by andreioprisan** [comment]
Sure, can you post a pull request and I'll merge it in?

**Comment by pigstake** [comment]
Any word on updating fourseven:scss to 3.1.1 and meta:susy to 2.1.1? :pray:

**Comment by andreioprisan** [comment]
Can you submit a pull request? Would be the fastest way to get this updated, otherwise I can push an update tomorrow.
